a = 'abcd'
print(a)
print(a+'5')
print(3*a)
print(a[0:5])
print(a[0:2])
print(a[0:1:3])
print('helloworld'[ : :-1])
print('helloworld'[1:9:2])
print('hello'[:-1])
print("-1 "+a[-1])
print('a' in a )
# print("la"*a)
a=5
print(a)
print(a+5)
print(3*a)